### PR TITLE
with LS and login

### PR DESCRIPTION
**Pull request by RasmusLAnd**

### CODE REVIEW

**Review by fonto1 — APPROVED** [review]

**Comment by fonto1** [comment]
seems like there is and error on row 80map, shall I add and if statement before merge?

**Comment by RasmusLAnd** [comment]
yes, please

Den tir. 15. okt. 2019 kl. 08.48 skrev fonto1 <notifications@github.com>:

**Comment by fonto1** [comment]
I have added an if statement, now the website should run

**Comment by fonto1** [comment]
I have also commented out the let data, now the site should use the empty data your created with ls instead

**Comment by fonto1** [comment]
try it out and merge if you thinks its ok

**Comment by fonto1** [comment]
on your ls you had localStorage.clear(); , that seems to stop the website from reloading data when we sign out/sign in

**Comment by RasmusLAnd** [comment]
that's strange - it work fine when I tried. LS.clear() was used to
overwrite with the new changes

Den tir. 15. okt. 2019 kl. 09.18 skrev fonto1 <notifications@github.com>:

**Comment by fonto1** [comment]
ahh I was confusing myself :D it works! shall we merge?

**Pull request merged**
